name: 'datawarehouse'
version: '1.0.0'

profile: 'datawarehouse'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  datawarehouse:
    +schema: dbo
    +materialized: view  # Define o materialization padrão para todas as models deste projeto
